-- AtmoSync telemetry table

CREATE TABLE IF NOT EXISTS TELEMETRY (
    DEVICE_ID VARCHAR(50),
    TIMESTAMP TIMESTAMP,
    TEMPERATURE_C FLOAT,
    HUMIDITY_PCT FLOAT,
    PRESSURE_HPA FLOAT
);

-- Check table structure/data
SELECT *
FROM TELEMETRY
LIMIT 20;
