-- AtmoSync hourly environmental metrics

SELECT
    DATE_TRUNC('HOUR', TIMESTAMP) AS TELEMETRY_HOUR,
    COUNT(*) AS PING_COUNT,
    ROUND(AVG(TEMPERATURE_C), 2) AS AVG_TEMP_C,
    ROUND(MAX(TEMPERATURE_C), 2) AS PEAK_TEMP_C,
    ROUND(MIN(TEMPERATURE_C), 2) AS MIN_TEMP_C,
    ROUND(AVG(HUMIDITY_PCT), 2) AS AVG_HUMIDITY_PCT,
    ROUND(AVG(PRESSURE_HPA), 2) AS AVG_PRESSURE_HPA
FROM TELEMETRY
GROUP BY DATE_TRUNC('HOUR', TIMESTAMP)
ORDER BY TELEMETRY_HOUR;
